# Generated by Django 6.0 on 2026-02-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(default='CASH', max_length=100),
        ),
    ]
