# Generated by Django 6.0 on 2026-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='upi_id',
            field=models.CharField(blank=True, help_text='e.g., coord@oksbi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upi_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qrs/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
