# Generated by Django 6.0 on 2026-03-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_upi_id_event_upi_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
